services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://aimudah:aimudah@db:5432/aimudah
      - NEXTAUTH_URL=https://aimudah.my.id
      - NEXTAUTH_SECRET=changeme
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=aimudah
      - POSTGRES_PASSWORD=aimudah
      - POSTGRES_DB=aimudah
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aimudah"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
